### ISSUE TITLE
Header section: Font size used for phone number should be 36px per design provided.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#3]
Font size used for IE7 is 28px while for IE8 is 32px

**Comment by rexcebudigital** [comment]
Wontfix: for IE versions, If we will not change the font-size, the layout will be distorted.. Every browser has its own padding and spacing.

**Comment by roseliesromeo** [comment]
I think we can adjust the spacing and padding. 8px is just too big a difference.

**Comment by rexcebudigital** [comment]
I have tried to adjust the spacing but still no good, so I just changed the font size for IE 8 and 7 in order to follow the psd design layout. This bug is a font bug, the font used is display differently for IE 8 and 7.
