### ISSUE TITLE
Contact Us modal: Input text is not centered.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#48]
![image](https://cloud.githubusercontent.com/assets/11186313/6592046/4dbd6466-c803-11e4-8546-0b91cbabf6ae.png)

IE browser

**Comment by roseliesromeo** [comment]
Input text still not vertically centered.

**Comment by rexcebudigital** [comment]
Centered on my end.

![screenshot3](https://cloud.githubusercontent.com/assets/11186391/6664901/a1042e84-cc0e-11e4-82c2-ca5edcd3f951.png)
