### ISSUE TITLE
Gallery page: Compact and Extended albums are not styled similarly as the gallery.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#51]
Album thumbnails are too small.

![image](https://cloud.githubusercontent.com/assets/11186313/6593177/f77a5bf0-c810-11e4-8e1e-cc5d1fcf7161.png)

**Comment by rexcebudigital** [comment]
I think the user is the one who will control the cover photo image on the backend side.

**Comment by rexcebudigital** [comment]
I set the min-width of the image to 190px
