### ISSUE TITLE
Contact Us: No need to display all information from the business details in front end if not shown in the design provided.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#61]
Currently, information like Postal address, admin email, Opening Hours and Fax Number are not there as per design PSD.

**Comment by rexcebudigital** [comment]
It will not display automatically if the client doesn't set business details, Example: if he put opening hours of course the opening hours will display.

**Comment by rexcebudigital** [comment]
Its not a bug on my end. 
![screenshot2](https://cloud.githubusercontent.com/assets/11186391/6664792/b05f18ae-cc0d-11e4-955d-95d5fb6ac7a3.png)

**Comment by roseliesromeo** [comment]
The email address reflected in Contact Us page is the admin email, not the enquiries email.

**Comment by rexcebudigital** [comment]
It is now set to inquiries email.
