### ISSUE TITLE
Lead-ins section: There is no hover state for the lead-ins.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#66]
Tab 3 (Portrait view)
iTouch 4
iPad air (Portrait view)

![image](https://cloud.githubusercontent.com/assets/11186313/6612602/5d03e8d4-c8ba-11e4-9ae8-37f65756c023.png)

**Comment by rexcebudigital** [comment]
Can I ask a screenshot for this?

**Comment by rexcebudigital** [comment]
There is a difference on the desktop view and mobile view..
