### ISSUE TITLE
Homepage: There is too much space gap between the image slider and the homepage content.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#67]
Samsung Tab3
Portrait view

![image](https://cloud.githubusercontent.com/assets/11186313/6610395/9782426a-c899-11e4-9fa4-3f43105b8ed1.png)

**Comment by roseliesromeo** [comment]
Issue still exist with below steps:
1. Switch orientation to landscape
2. Go back to portrait view.

**Comment by rexcebudigital** [comment]
Its not a bug on my end. Please recheck. Thanks
![screenshot1](https://cloud.githubusercontent.com/assets/11186391/6664725/2eade3da-cc0d-11e4-9acf-9395f841ef8d.png)

**Comment by roseliesromeo** [comment]
Yes I am still able to replicate using the same steps above.
![image](https://cloud.githubusercontent.com/assets/11186313/6679659/11a8567a-cc86-11e4-86ee-27fa7bbef1a6.png)

**Comment by rexcebudigital** [comment]
Please wait for the time that I re assign activ collab to you mam. Thanks.

**Comment by roseliesromeo** [comment]
Issue still exists.

**Comment by rexcebudigital** [comment]
I've tried it on my end several times. And I've been assuming some bugs here.. Please check miss. I made changes for it. thanks.

**Comment by roseliesromeo** [comment]
Issue now exists in desktop view.
IE7

**Comment by roseliesromeo** [comment]
IE7
This was already fixed but exists again.

![image](https://cloud.githubusercontent.com/assets/11186313/6722632/279a4bda-ce18-11e4-8a79-7f240162c142.png)
