### ISSUE TITLE
Header section: Email contact link is using the Admin email instead of the Enquiries email of the business details.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#7]
As per standards:

Default Contact Number link will be from the Business Details Phone Number field.
Default Email link will be from the Business Details Enquiries Email field.

**Comment by roseliesromeo** [comment]
Email contact link is still using the Business Details - Admin email.

**Comment by rexcebudigital** [comment]
It uses info@infinityflooring.com.au, on the design brief theres no client supplied email. Its just info@infinityflooring.com.au. Or can you explain further about this bug?

**Comment by roseliesromeo** [comment]
The email address used here is taken from the business details - admin email field.  It should be from business details - enquiries email.
