### ISSUE TITLE
Gallery page: There is space gap between gallery images.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#70]
iPad air
Samsung Tab3 (landscape view)

![image](https://cloud.githubusercontent.com/assets/11186313/6610745/d5382e44-c89e-11e4-8de6-4855314dbca7.png)

**Comment by roseliesromeo** [comment]
Issue still exist for the same devices mentioned.

**Comment by rexcebudigital** [comment]
The display images per page is 15, so there will be a space when the gallery is devisible by 2. If you count the images the output would be 15.

**Comment by roseliesromeo** [comment]
Display of images should be fluid as well.  No gap in between.

**Comment by roseliesromeo** [comment]
I suggest to have it displayed in 4 rows by 3 columns to have an even number of images page.

**Comment by rexcebudigital** [comment]
Better suggestion.

**Comment by rexcebudigital** [comment]
But really doing that? Its like not following the design flow.
