### ISSUE TITLE
Header section: Enclosing parenthesis in the phone area code has been removed.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#84]
Applicable in Contact Us page.

![image](https://cloud.githubusercontent.com/assets/11186313/6684296/e1c7c2e8-ccca-11e4-807e-bc11e7cd5b37.png)

**Comment by rexcebudigital** [comment]
No parenthesis on the psd design.

**Comment by roseliesromeo** [comment]
It is the standard implementation for phone number to enclose area code in parenthesis.
