### ISSUE TITLE
Homepage: Some text missing from the home page title/content.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Infinity-Flooring#86]
![image](https://cloud.githubusercontent.com/assets/11186313/6684758/24eb8682-cccf-11e4-8a2e-5b3cf5f0f8c6.png)

**Comment by roseliesromeo** [comment]
I don't think we need to add another field for this.  I believe this is part of H1.

**Comment by rexcebudigital** [comment]
Nope, I insist for the H1, Since the content is on the right side, and if it was H1 it will be on the right side too, In our coding, to make it display on screen is <?php the_content(); ?> and if H1 it should be on the right side. So its better to add another field for this. Thanks.
